# Updated with your official Project Key
sonar.projectKey=MDL-ECOM-ANDROID
sonar.projectName=MDL-ECOM-ANDROID
sonar.projectVersion=1.0.0
sonar.sources=lib
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*
sonar.dart.lcov.reportPath=
sonar.dart.analysis.reportPath=.dart_tool/flutter_tester/analysis_report.json
sonar.exclusions=android/**, ios/**, web/**, windows/**, build/**, **/*.g.dart, lib/generated_plugin_registrant.dart